name: takhfid_client
description: تطبيق العميل Flutter للتخفيض الصح
publish_to: none
version: 1.0.0+3

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^11.2.0
  cached_network_image: ^4.0.0
  path_provider: ^2.1.6
  image_picker: ^1.2.3
  video_player: ^2.14.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#08080A"
  adaptive_icon_foreground: "assets/icon.png"
