name: takhfid_client
description: تطبيق العميل Flutter للتخفيض الصح
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
